dist: xenial

language: minimal

matrix:
    include:
        - os: linux
          env: PYENV=py37
        - os: linux
          env: PYENV=py27
        - os: osx
          env: PYENV=py37
        - os: osx
          env: PYENV=py27
# turn these on once travis support gets a little better, see pyam for example
#        - os: windows
#          env: PYENV=py37
#        - os: windows
#          env: PYENV=py27

addons:
  apt:
    packages:
    # For building R packages
    - r-base-dev
    # Dependencies of devtools, to avoid rebuilding
    - r-cran-callr
    - r-cran-cli
    - r-cran-digest
    - r-cran-git2r
    - r-cran-httr
    - r-cran-jsonlite
    - r-cran-memoise
    - r-cran-pkgbuild
    - r-cran-pkgload
    - r-cran-rcmdcheck
    - r-cran-remotes
    - r-cran-rstudioapi
    - r-cran-sessioninfo
    - r-cran-usethis
    - r-cran-withr

before_install:
  - source ./ci/env.sh
  - bash ./ci/travis-install.sh
  - source activate testing

install:
  - python setup.py install
  - Rscript -e 'devtools::install_dev_deps("retixmp/source")'

script:
  - python -c "import os, sys; assert os.environ['PYVERSION'] == sys.version[0]"
  # Python tests; these include equivalent of the Travis R tests via test_r.py
  - >
    pytest
    --verbose
    --cov=ixmp
    --cov-config ci/.coveragerc
    --cov-report term-missing
  # Test that documentation can be built
  - cd doc
  - pip install -r requirements.txt
  - make html

after_success:
  - coveralls
