# Continuous integration procedure for AppVeyor
# Based on https://github.com/rmcgibbo/python-appveyor-conda-example

environment:
  matrix:
      - PYTHON_VERSION: "2.7"
        MINICONDA: "C:\\Miniconda-x64"
        PYTHON_ARCH: "64"
      - PYTHON_VERSION: "3.6"
        MINICONDA: "C:\\Miniconda36-x64"
        PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"
  # r-appveyor
  - ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.githubusercontent.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  # these correspond to folder naming of miniconda installs on appveyor.  See
  # https://www.appveyor.com/docs/installed-software#python
  - if "%PYTHON_VERSION%" == "3.6" set "BASE_PYTHON_VERSION=36"
  - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
  # These are already installed on appveyor.  Update them.
  - set "CONDA_ROOT=C:\Miniconda%BASE_PYTHON_VERSION%%ARCH_LABEL%"
  - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"

  # Dependencies and package install
  - ps: Start-FileDownload 'https://d37drm4t2jghv5.cloudfront.net/distributions/25.1.1/windows/windows_x64_64.exe'
  - windows_x64_64.exe /SP- /VERYSILENT /NORESTART /DIR=.\gams /NOICONS
  - "SET PATH=%cd%\\gams;%PATH%"
  - conda install --yes -c conda-forge ixmp
  - conda remove --force --yes ixmp

  # r-appveyor
  - ps: Bootstrap

  - python setup.py install

build: false

test_script:
  - conda install --yes -c conda-forge pytest
  - pytest -v tests --win_ci_skip

on_success:
  - echo Build succesful!

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
